### ISSUE TITLE
[BUG] Pytorch Installation Issue 

### ISSUE THREAD

**Issue by jialincheoh** [ironhacks/ironhub#13]
A participant asking why Pytorch is not working for her. 

Pytorch installation stopped working for me today. 

<img width="1097" alt="Screenshot 2022-11-16 at 11 25 03 PM" src="https://user-images.githubusercontent.com/19192631/202221760-39613d3b-5b2d-4e16-9c97-243abd54b9a7.png">

A few days ago it was working 

<img width="1048" alt="Screenshot 2022-11-16 at 11 26 27 PM" src="https://user-images.githubusercontent.com/19192631/202222120-c5c01c4d-2482-4347-ab78-275ed5506d88.png">

**Comment by ManthanKeim** [comment]
this is because this participant's instance is running low on memory, so I just found the solution if someone cannot install package by normal pip command, they need to run this with these arguments:

`pip install PACKAGE_NAME --no-cache-dir
`
