### ISSUE TITLE
Get familiar with helms to work migration to RCAC/Gedes

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/ironhub#2]
1. Goal: We want to move to Gedes system (internal Purdue system)
2. Problem: Manthan and Sabine need to understand how it works (and Harsha)?
3. Next steps: Reach out to Eric to ask for a meeting for help, read documentation, and try to put hub on gedes! 
We asked for a meeting or documentation from Erik. (awaiting reply)

4. Misc?

**Comment by ManthanKeim** [comment]
# First Meeting with Brian and Manthan/jupyterhub/geddes walkthrough on 07/12/2021 - 11AM EST

We started by talking about how our basic platform works, gave brief about IronHacks and then shifted to ironhub, as that's our priority now to migrate it to geddes.

Brian gave me a detailed walkthrough of the platform, hosted a jupyterhub, still needs to figure out the authentication method for participants. 

https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html

Brian will share a documentation in next 24 hour on how to setup the jupyterhub on geddes.

Libraries need to be installed before working:
helm and kubectl

## Keywords
helm
kuberconfig file
cd .kube/
cat config
cd jupyterhub
config.yaml
service-discovery

## Screenshots: 

![Screenshot 2021-07-12 at 9 13 48 PM](https://user-images.githubusercontent.com/23071741/125337574-cd950280-e36c-11eb-93ee-ef1060e15fce.png)

![Screenshot 2021-07-12 at 8 49 58 PM](https://user-images.githubusercontent.com/23071741/125337727-f4ebcf80-e36c-11eb-92ee-06233e8a479f.png)

## Next Step

Read the documentation and setup a notebook.

**Comment by ManthanKeim** [comment]
# Base jupyterhub hosted on Geddes accessed globally

## Some sleeping issues like heroku are there, mailed Eric and Brian and we'll see how to overcome that.

## URL: http://proxy-public.test-ns.geddes.rcac.purdue.edu

**Comment by ManthanKeim** [comment]
Latest Ironhub live at: ironhub.live

Doing customisations like installing libraries, accessing participants notebook at random time.

**Comment by ManthanKeim** [comment]
<img width="1792" alt="Screenshot 2021-09-11 at 21 00 49" src="https://user-images.githubusercontent.com/23071741/132967257-114a4049-91ca-4a53-9765-3d5831cc3d43.png">

Update as of Sep 11 - https://ironhub.live is live handling almost 50 pods/notebooks at a time. Admins can access notebooks of other users admin/non-admin at any moment to either fix bugs or observations.

Next Steps: Record the history of each live notebook cells with timestamps and integrate it with the database either SQLite/MongoDB or any other which is supported.

**Comment by ManthanKeim** [comment]
Database and python history can be accessed with Kubernetes, have asked for admin access from Erik/Biran. 


https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/
