### ISSUE TITLE
Server Asking to Restart After About 20 minutes

### ISSUE THREAD

**Issue by jialincheoh** [ironhacks/ironhub#8]
**Describe the bug**

When we use the GPU option in the notebook, the server stops working after approx 20 - 30 minutes. It's asking us to restart the server with a "File Save Error". Refer to the screenshot below. 

Exact Error Message in the middle of running the notebook

```
Your server at XXXX is not running. Would you like to restart it? 
```

**To Reproduce**
1. Go to 'https://ironhub.live/user/jialincheoh9@gmail.com/lab/workspaces/auto-g/tree/Fuzzy-Logic.ipynb'
2. Run the notebook

**Expected behavior**
The notebook should run without asking to restart the server. 

**Screenshots**

<img width="1749" alt="Screenshot 2022-06-27 at 10 49 57 PM" src="https://user-images.githubusercontent.com/19192631/175983120-122202ff-1dc8-4881-8104-b27219f72f3c.png">
<img width="824" alt="Screenshot 2022-06-27 at 11 34 41 PM" src="https://user-images.githubusercontent.com/19192631/175983125-fb2b6246-e06a-49e6-95c5-dbd9c0f2210a.png">
<img width="935" alt="Screenshot 2022-06-27 at 11 40 40 PM" src="https://user-images.githubusercontent.com/19192631/175983131-f704cf4f-9276-4877-9dea-258a8e7fcdf2.png">
<img width="1283" alt="Screenshot 2022-06-27 at 10 49 45 PM" src="https://user-images.githubusercontent.com/19192631/175983106-2d922cd9-aef0-4efd-88b1-cc3c9b01a4da.png">

**Comment by ManthanKeim** [comment]
There can be two reasons for this error: 
1. Limited memory storage of the notebook
2. Inactivity - there is no option right now where you can just leave your notebook to run for a long time, you have to monitor it frequently(click on it) to keep it running.

**Comment by ManthanKeim** [comment]
Closing as we will solve this while Transitioning to stable Geddes.
