### ISSUE TITLE
[ASAP] [Bug] "db-dtypes" package not found

### ISSUE THREAD

**Issue by harshpavuluri** [ironhacks/ironhub#9]
Summary: 

When running the query command to convert the returned query to a dataframe, the ""db-dtypes" package needs to be installed" message appears.

- [ ] Solve issue with the docker image so that all necessary packages for the python libraries are installed

**Comment by ManthanKeim** [comment]
This will be installed in the next update of Ironhub, request more library if needed,

https://github.com/ironhacks/ironhub/blob/master/libraries_need_to_be_installed

**Comment by harshpavuluri** [comment]
Resolved with manual user input. Closing
